### PR TITLE
Add silencer gem in order to prevent flooding logfiles 

### LINKED ISSUE #10: Add silencer gem in order to prevent flooding logfiles.

### PR DESCRIPTION
**Pull request by 6temes**
Fix #10

### CODE REVIEW

**Comment by 6temes** [comment]
@kenjiszk I added the silencer gem in the finc_health_care gem. That way, it will not "pollute" the logs of the servers. 

I think that it will be better if you review this PR commit by commit because I did some cleanup as well.

**Comment by 6temes** [comment]
I tested it with Mailer in Staging, by the way.

**Comment by 6temes** [comment]
@kenjiszk Ping

**Comment by kenjiszk** [comment]
Sorry for late!
Thanks!

**Pull request merged**
